name: CI/CD do Jornal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # permite rodar manualmente

# evita deploys concorrentes no mesmo branch
concurrency:
  group: prod-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do Repositório (histórico completo p/ métricas)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Executar Testes
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # só roda se os testes passarem
    environment: production
    
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        id: deploy
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Notify Sleuth via cURL (Fix 401)
        if: ${{ success() && steps.deploy.outcome == 'success' }}
        run: |
          API_URL="https://app.sleuth.io/api/1/deployments/fatec-matao-luiz-marchesan/pipeline-app/register_deploy"
          
          # Construindo o corpo JSON com os dados do deploy
          PAYLOAD='{
            "sha": "${{ github.sha }}",
            "environment": "production",
            "email": "nevesisabela03@gmail.com"
          }'

          # Enviando a requisição com o formato de autenticação "apikey"
          curl -X POST \
            -H "Authorization: apikey ${{ secrets.SLEUTH_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "$API_URL"
