name: Deploy Pipeline

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4               
          
      - name: Test Sleuth Deploy via cURL
        run: |
          curl -X POST \
          "https://app.sleuth.io/api/1/deployments/fatec-matao-luiz-marchesan/pipeline-app/register_deploy" \
          -H "Content-Type: application/json" \
          -d "{
                \"api_key\": \"${{ secrets.SLEUTH_API_KEY }}\",
                \"sha\": \"${{ github.sha }}\",
                \"environment\": \"production\",
                \"email\": \"nevesisabela03@gmail.com\"
              }"    

